### ISSUE TITLE
Reading Parquet files using Snappy compression from S3 does not work

### ISSUE THREAD

**Issue by robvadai** [smizy/docker-apache-drill#3]
When using a S3 data source and reading Snappy compressed Parquet files generated by Spark SQL 2.2.0 I got the following error in the logs:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
```

The problem might not be with S3 but rather some incompatibility with the Java Snappy library but I thought I share what my data source was.
Drill works fine when tested from a MacOS High Sierra (version 10.13.1) system so I suspect the issue is to do with Alpine and Snappy.

**Comment by smizy** [comment]
@robvadai 
I fixed native snappy lib loading error.
Could you try docker image "smizy/apache-drill:1.12.0-alpine-r1".

**Comment by robvadai** [comment]
I've tested the new version and it works perfectly!
Thank you for your swift response & fix!
